CREATE SEQUENCE Types_seq;

CREATE TABLE Types(
ID int DEFAULT TYPES_SEQ.nextval not null,
Type VARCHAR2(30),
PRIMARY KEY(ID));

INSERT INTO types(Type)VALUES('One');

SELECT * FROM Types;


CREATE FUNCTION get_types_seq RETURN NUMBER IS
BEGIN
RETURN Types_seq.nextval;
END;
--NOT WORKING BY INSERT ALL
INSERT ALL
INTO types(ID,Type) VALUES(get_types_seq,'Two')
INTO types(ID,Type) VALUES(get_types_seq,'Three')
SELECT * FROM DUAL;
/
CREATE OR REPLACE TRIGGER types_om_insert
BEFORE INSERT ON Types
FOR EACH ROW
BEGIN
SELECT Types_seq.nextval
INTO:new.id
FROM dual;
END;
/
exec types_om_seq('Four');
/
DROP TABLE Types;
/
CREATE TABLE Types(
ID INT GENERATED BY DEFAULT ON NULL AS IDENTITY,
Type VARCHAR(30),
PRIMARY KEY(ID));

INSERT ALL
INTO types(ID,Type) VALUES(get_types_seq,'One')
INTO types(ID,Type) VALUES(get_types_seq,'Two')
INTO types(ID,Type) VALUES(get_types_seq,'Three')
SELECT * FROM DUAL;
/

SELECT * FROM v$version
WHERE banner LIKE 'Oracle%';
/
SELECT CEIL(comm),comm FROM salespeople;
/
SELECT FLOOR(comm),comm FROM salespeople;
/
SELECT TRUNC(comm,1),comm FROM salespeople;
/
SELECT ROUND(comm,1),comm FROM salespeople;
/
SELECT SIGN(comm),comm FROM salespeople;
/
SELECT ASCII(sname) FROM salespeople;
/
SELECT CONCAT('$', TO_CHAR(comm))FROM salespeople; 

SELECT UPPER(sname), LOWER(city) FROM salespeople;

SELECT SYSTIMESTAMP "date" FROM DUAL;

SELECT  CURRENT_TIMESTAMP  FROM DUAL;

SELECT TO_CHAR(SYSDATE,'DD-DAY-MONTH-YEAR') LONG_DATE FROM DUAL;




















